# Generated by Django 5.0.4 on 2024-05-18 13:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_appointment', models.CharField(max_length=100)),
                ('hora', models.IntegerField()),
                ('especialidade', models.IntegerField()),
                ('medico', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=100)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Consultas',
            },
        ),
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
