# Generated by Django 5.0.4 on 2024-05-18 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_consultas_delete_appointment'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='consultas',
            table='consultas',
        ),
    ]
