# Generated by Django 5.0.4 on 2024-05-18 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_alter_consultas_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consultas',
            old_name='user_id',
            new_name='user',
        ),
    ]
